// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuhasebeStokWebApp.Data;

#nullable disable

namespace MuhasebeStokWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Banka", b =>
                {
                    b.Property<Guid>("BankaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("AcilisBakiye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("BankaAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("GuncelBakiye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HesapNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("TRY");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubeAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubeKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("YetkiliKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BankaID");

                    b.ToTable("Bankalar");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.BankaHareket", b =>
                {
                    b.Property<Guid>("BankaHareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("BankaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CariID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DekontNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HareketTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("HedefKasaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IslemYapanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KarsiBankaAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KarsiIBAN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KarsiUnvan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("KaynakKasaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReferansID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferansNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferansTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TransferID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BankaHareketID");

                    b.HasIndex("BankaID");

                    b.HasIndex("CariID");

                    b.HasIndex("HedefKasaID");

                    b.HasIndex("KaynakKasaID");

                    b.ToTable("BankaHareketleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Birim", b =>
                {
                    b.Property<Guid>("BirimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("BirimID");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Cari", b =>
                {
                    b.Property<Guid>("CariID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CariAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Yetkili")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CariID");

                    b.ToTable("Cariler");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.CariHareket", b =>
                {
                    b.Property<Guid>("CariHareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CariID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HareketTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("IslemYapanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReferansID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferansNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferansTuru")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CariHareketID");

                    b.HasIndex("CariID");

                    b.ToTable("CariHareketler");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Depo", b =>
                {
                    b.Property<Guid>("DepoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("DepoAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DepoID");

                    b.ToTable("Depolar");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.DovizIliski", b =>
                {
                    b.Property<Guid>("DovizIliskiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HedefParaBirimiID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KaynakParaBirimiID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParaBirimiID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParaBirimiID1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("DovizIliskiID");

                    b.HasIndex("HedefParaBirimiID");

                    b.HasIndex("KaynakParaBirimiID");

                    b.HasIndex("ParaBirimiID");

                    b.HasIndex("ParaBirimiID1");

                    b.ToTable("DovizIliskileri", (string)null);
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Fatura", b =>
                {
                    b.Property<Guid>("FaturaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("AraToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CariID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DovizKuru")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DovizTuru")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FaturaNotu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FaturaNumarasi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FaturaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FaturaTuruID")
                        .HasColumnType("int");

                    b.Property<decimal?>("GenelToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("KDVToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OdemeDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OdemeTuruID")
                        .HasColumnType("int");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Resmi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SiparisNumarasi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VadeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("FaturaID");

                    b.HasIndex("CariID");

                    b.HasIndex("FaturaTuruID");

                    b.HasIndex("OdemeTuruID");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.FaturaDetay", b =>
                {
                    b.Property<Guid>("FaturaDetayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Birim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BirimID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FaturaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IndirimOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IndirimTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KdvTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SatirKdvToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatirToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UrunID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FaturaDetayID");

                    b.HasIndex("BirimID");

                    b.HasIndex("FaturaID");

                    b.HasIndex("UrunID");

                    b.ToTable("FaturaDetaylari");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.FaturaOdeme", b =>
                {
                    b.Property<Guid>("OdemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FaturaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdemeTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("OdemeTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OdemeID");

                    b.HasIndex("FaturaID");

                    b.ToTable("FaturaOdemeleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.FaturaTuru", b =>
                {
                    b.Property<int>("FaturaTuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaturaTuruID"));

                    b.Property<string>("FaturaTuruAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HareketTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FaturaTuruID");

                    b.ToTable("FaturaTurleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.FiyatTipi", b =>
                {
                    b.Property<int>("FiyatTipiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FiyatTipiID"));

                    b.Property<string>("TipAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FiyatTipiID");

                    b.ToTable("FiyatTipleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Irsaliye", b =>
                {
                    b.Property<Guid>("IrsaliyeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CariID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("FaturaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("GenelToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IrsaliyeNumarasi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("IrsaliyeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IrsaliyeTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IrsaliyeTuruID")
                        .HasColumnType("int");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Resmi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("SevkTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IrsaliyeID");

                    b.HasIndex("CariID");

                    b.HasIndex("FaturaID");

                    b.HasIndex("IrsaliyeTuruID");

                    b.ToTable("Irsaliyeler");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.IrsaliyeDetay", b =>
                {
                    b.Property<Guid>("IrsaliyeDetayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("BirimID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IrsaliyeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SatirKdvToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatirToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UrunID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IrsaliyeDetayID");

                    b.HasIndex("BirimID");

                    b.HasIndex("IrsaliyeID");

                    b.HasIndex("UrunID");

                    b.ToTable("IrsaliyeDetaylari");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.IrsaliyeTuru", b =>
                {
                    b.Property<int>("IrsaliyeTuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IrsaliyeTuruID"));

                    b.Property<string>("HareketTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IrsaliyeTuruAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IrsaliyeTuruID");

                    b.ToTable("IrsaliyeTurleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Kasa", b =>
                {
                    b.Property<Guid>("KasaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("AcilisBakiye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("GuncelBakiye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KasaAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KasaTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SorumluKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KasaID");

                    b.ToTable("Kasalar");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.KasaHareket", b =>
                {
                    b.Property<Guid>("KasaHareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CariID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DovizKuru")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HareketTuru")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("HedefBankaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HedefKasaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("IslemYapanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KarsiParaBirimi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("KasaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KaynakBankaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReferansID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferansNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferansTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TransferID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("KasaHareketID");

                    b.HasIndex("CariID");

                    b.HasIndex("HedefBankaID");

                    b.HasIndex("HedefKasaID");

                    b.HasIndex("KasaID");

                    b.HasIndex("KaynakBankaID");

                    b.ToTable("KasaHareketleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.KurDegeri", b =>
                {
                    b.Property<Guid>("KurDegeriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DovizKuruID");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Aciklama");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("AlisDegeri")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("AlisFiyati");

                    b.Property<decimal>("Deger")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("KurDegeri");

                    b.Property<Guid?>("DovizIliskiID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Manuel")
                        .HasColumnName("Kaynak");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParaBirimiID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("SatisDegeri")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("SatisFiyati");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("KurDegeriID");

                    b.HasIndex("DovizIliskiID");

                    b.HasIndex("ParaBirimiID");

                    b.ToTable("DovizKurlari", (string)null);
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.OdemeTuru", b =>
                {
                    b.Property<int>("OdemeTuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdemeTuruID"));

                    b.Property<string>("OdemeTuruAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OdemeTuruID");

                    b.ToTable("OdemeTurleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.ParaBirimi", b =>
                {
                    b.Property<Guid>("ParaBirimiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DovizID");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DovizAdi");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("DovizKodu");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sembol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Sembol");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ParaBirimiID");

                    b.ToTable("Dovizler", (string)null);
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.SistemAyarlari", b =>
                {
                    b.Property<Guid>("SistemAyarlariID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("AktifParaBirimleri")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("USD,EUR,TRY,UZS,GBP");

                    b.Property<string>("AnaDovizKodu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("USD");

                    b.Property<Guid?>("AnaParaBirimiID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DovizGuncellemeSikligi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IkinciDovizKodu")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("UZS");

                    b.Property<Guid?>("IkinciParaBirimiID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OtomatikDovizGuncelleme")
                        .HasColumnType("bit");

                    b.Property<string>("SirketAdi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Şirket");

                    b.Property<string>("SirketAdresi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasDefaultValue("");

                    b.Property<string>("SirketEmail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("SirketTelefon")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("SirketVergiDairesi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("SirketVergiNo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SonDovizGuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("UcuncuDovizKodu")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("TRY");

                    b.Property<Guid?>("UcuncuParaBirimiID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SistemAyarlariID");

                    b.HasIndex("AnaParaBirimiID");

                    b.HasIndex("IkinciParaBirimiID");

                    b.HasIndex("UcuncuParaBirimiID");

                    b.ToTable("SistemAyarlari");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.SistemLog", b =>
                {
                    b.Property<Guid>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Basarili")
                        .HasColumnType("bit");

                    b.Property<string>("HataMesaji")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IPAdresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IlgiliID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KayitAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("KayitID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KullaniciID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<string>("TabloAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tarayici")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("LogID");

                    b.ToTable("SistemLoglar");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.StokFifo", b =>
                {
                    b.Property<Guid>("StokFifoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DovizKuru")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Iptal")
                        .HasColumnType("bit");

                    b.Property<string>("IptalAciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("IptalEdenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("IptalTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KalanMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("ReferansID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferansNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferansTuru")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SonCikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TLBirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("USDBirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UZSBirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UrunID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StokFifoID");

                    b.HasIndex("GirisTarihi")
                        .HasDatabaseName("IX_StokFifo_GirisTarihi");

                    b.HasIndex("UrunID")
                        .HasDatabaseName("IX_StokFifo_UrunID");

                    b.HasIndex("ReferansID", "ReferansTuru")
                        .HasDatabaseName("IX_StokFifo_Referans");

                    b.HasIndex("UrunID", "KalanMiktar", "Aktif", "SoftDelete", "Iptal")
                        .HasDatabaseName("IX_StokFifo_StokSorgu");

                    b.ToTable("StokFifo");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.StokHareket", b =>
                {
                    b.Property<Guid>("StokHareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("DepoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FaturaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HareketTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("IrsaliyeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IslemYapanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReferansID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferansNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferansTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UrunID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StokHareketID");

                    b.HasIndex("DepoID");

                    b.HasIndex("UrunID");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Urun", b =>
                {
                    b.Property<Guid>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("BirimID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("KategoriID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StokMiktar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrunKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UrunID");

                    b.HasIndex("BirimID");

                    b.HasIndex("KategoriID");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.UrunFiyat", b =>
                {
                    b.Property<int>("FiyatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FiyatID"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FiyatTipiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GecerliTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UrunID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FiyatID");

                    b.HasIndex("FiyatTipiID");

                    b.HasIndex("UrunID");

                    b.ToTable("UrunFiyatlari");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.UrunKategori", b =>
                {
                    b.Property<Guid>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("OlusturanKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SonGuncelleyenKullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KategoriID");

                    b.ToTable("UrunKategorileri");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.BankaHareket", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Banka", "Banka")
                        .WithMany("BankaHareketleri")
                        .HasForeignKey("BankaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Kasa", "HedefKasa")
                        .WithMany()
                        .HasForeignKey("HedefKasaID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Kasa", "KaynakKasa")
                        .WithMany()
                        .HasForeignKey("KaynakKasaID");

                    b.Navigation("Banka");

                    b.Navigation("Cari");

                    b.Navigation("HedefKasa");

                    b.Navigation("KaynakKasa");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.CariHareket", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Cari", "Cari")
                        .WithMany("CariHareketleri")
                        .HasForeignKey("CariID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.DovizIliski", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.ParaBirimi", "HedefParaBirimi")
                        .WithMany()
                        .HasForeignKey("HedefParaBirimiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.ParaBirimi", "KaynakParaBirimi")
                        .WithMany()
                        .HasForeignKey("KaynakParaBirimiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.ParaBirimi", null)
                        .WithMany("HedefDovizIliskileri")
                        .HasForeignKey("ParaBirimiID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.ParaBirimi", null)
                        .WithMany("KaynakDovizIliskileri")
                        .HasForeignKey("ParaBirimiID1");

                    b.Navigation("HedefParaBirimi");

                    b.Navigation("KaynakParaBirimi");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Fatura", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Cari", "Cari")
                        .WithMany("Faturalar")
                        .HasForeignKey("CariID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.FaturaTuru", "FaturaTuru")
                        .WithMany("Faturalar")
                        .HasForeignKey("FaturaTuruID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.OdemeTuru", "OdemeTuru")
                        .WithMany("Faturalar")
                        .HasForeignKey("OdemeTuruID");

                    b.Navigation("Cari");

                    b.Navigation("FaturaTuru");

                    b.Navigation("OdemeTuru");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.FaturaDetay", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Birim", null)
                        .WithMany("FaturaDetaylari")
                        .HasForeignKey("BirimID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Fatura", "Fatura")
                        .WithMany("FaturaDetaylari")
                        .HasForeignKey("FaturaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Urun", "Urun")
                        .WithMany("FaturaDetaylari")
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.FaturaOdeme", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Fatura", "Fatura")
                        .WithMany("FaturaOdemeleri")
                        .HasForeignKey("FaturaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Irsaliye", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Fatura", "Fatura")
                        .WithMany("Irsaliyeler")
                        .HasForeignKey("FaturaID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.IrsaliyeTuru", null)
                        .WithMany("Irsaliyeler")
                        .HasForeignKey("IrsaliyeTuruID");

                    b.Navigation("Cari");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.IrsaliyeDetay", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Birim", null)
                        .WithMany("IrsaliyeDetaylari")
                        .HasForeignKey("BirimID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Irsaliye", "Irsaliye")
                        .WithMany("IrsaliyeDetaylari")
                        .HasForeignKey("IrsaliyeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Irsaliye");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.KasaHareket", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Banka", "HedefBanka")
                        .WithMany()
                        .HasForeignKey("HedefBankaID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Kasa", "HedefKasa")
                        .WithMany()
                        .HasForeignKey("HedefKasaID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Kasa", "Kasa")
                        .WithMany("KasaHareketleri")
                        .HasForeignKey("KasaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Banka", "KaynakBanka")
                        .WithMany()
                        .HasForeignKey("KaynakBankaID");

                    b.Navigation("Cari");

                    b.Navigation("HedefBanka");

                    b.Navigation("HedefKasa");

                    b.Navigation("Kasa");

                    b.Navigation("KaynakBanka");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.KurDegeri", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.DovizIliski", "DovizIliski")
                        .WithMany()
                        .HasForeignKey("DovizIliskiID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.ParaBirimi", "ParaBirimi")
                        .WithMany()
                        .HasForeignKey("ParaBirimiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DovizIliski");

                    b.Navigation("ParaBirimi");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.SistemAyarlari", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.ParaBirimi", "AnaParaBirimi")
                        .WithMany()
                        .HasForeignKey("AnaParaBirimiID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.ParaBirimi", "IkinciParaBirimi")
                        .WithMany()
                        .HasForeignKey("IkinciParaBirimiID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.ParaBirimi", "UcuncuParaBirimi")
                        .WithMany()
                        .HasForeignKey("UcuncuParaBirimiID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AnaParaBirimi");

                    b.Navigation("IkinciParaBirimi");

                    b.Navigation("UcuncuParaBirimi");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.StokFifo", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.StokHareket", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Depo", "Depo")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("DepoID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Urun", "Urun")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depo");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Urun", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Birim", "Birim")
                        .WithMany("Urunler")
                        .HasForeignKey("BirimID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.UrunKategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriID");

                    b.Navigation("Birim");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.UrunFiyat", b =>
                {
                    b.HasOne("MuhasebeStokWebApp.Data.Entities.FiyatTipi", "FiyatTipi")
                        .WithMany("UrunFiyatlari")
                        .HasForeignKey("FiyatTipiID");

                    b.HasOne("MuhasebeStokWebApp.Data.Entities.Urun", "Urun")
                        .WithMany("UrunFiyatlari")
                        .HasForeignKey("UrunID");

                    b.Navigation("FiyatTipi");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Banka", b =>
                {
                    b.Navigation("BankaHareketleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Birim", b =>
                {
                    b.Navigation("FaturaDetaylari");

                    b.Navigation("IrsaliyeDetaylari");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Cari", b =>
                {
                    b.Navigation("CariHareketleri");

                    b.Navigation("Faturalar");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Depo", b =>
                {
                    b.Navigation("StokHareketleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Fatura", b =>
                {
                    b.Navigation("FaturaDetaylari");

                    b.Navigation("FaturaOdemeleri");

                    b.Navigation("Irsaliyeler");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.FaturaTuru", b =>
                {
                    b.Navigation("Faturalar");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.FiyatTipi", b =>
                {
                    b.Navigation("UrunFiyatlari");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Irsaliye", b =>
                {
                    b.Navigation("IrsaliyeDetaylari");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.IrsaliyeTuru", b =>
                {
                    b.Navigation("Irsaliyeler");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Kasa", b =>
                {
                    b.Navigation("KasaHareketleri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.OdemeTuru", b =>
                {
                    b.Navigation("Faturalar");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.ParaBirimi", b =>
                {
                    b.Navigation("HedefDovizIliskileri");

                    b.Navigation("KaynakDovizIliskileri");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.Urun", b =>
                {
                    b.Navigation("FaturaDetaylari");

                    b.Navigation("StokHareketleri");

                    b.Navigation("UrunFiyatlari");
                });

            modelBuilder.Entity("MuhasebeStokWebApp.Data.Entities.UrunKategori", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
